name: Build Preview

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: helaili/jekyll-action@2.0.5
        with:
          pre_build_commands: |
            gem update --system 3.3.22
          build_only: true
